version: "2"
services:
    service-a:
        build: ./service-a
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        labels:
            com.microsoft.azure.public.port: "80"
        ports:
            - "8080:80"
        links:
            - service-b
    
    service-b:
        build: ./service-b
            context: .
            args:
                - TESTVAR=original
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
            - TESTVAR=original
        expose:
            - 80
